export * from "./user";
export * from "./question";
export * from "./subject"
export * from './adduser';
export * from './examlist';
export * from './student';
export * from './room';
export * from './stulist/allstu';
export * from './addclass';
